# Generated by Django 5.1.6 on 2025-03-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=90)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=2000)),
                ('autor', models.CharField(max_length=90)),
                ('imagen', models.ImageField(upload_to='imagenesNews/')),
                ('publicado', models.BooleanField(default=True)),
            ],
        ),
    ]
